### ISSUE TITLE
Table_Summary throws java.lang.OutOfMemoryError: Java heap space  

### ISSUE THREAD

**Issue by M4tt30rru** [SpartanRefactoring/Main#1307]
This is the stacktrace

  ```1...Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
	at java.util.Arrays.copyOf(Arrays.java:3332)
	at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:124)
	at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:448)
	at java.lang.StringBuilder.append(StringBuilder.java:136)
	at il.org.spartan.utils.FileUtils.read(FileUtils.java:42)
	at il.org.spartan.spartanizer.cmdline.ASTInFilesVisitor.productionCode(ASTInFilesVisitor.java:69)
	at il.org.spartan.spartanizer.cmdline.ASTInFilesVisitor.visitFile(ASTInFilesVisitor.java:134)
	at il.org.spartan.spartanizer.cmdline.ASTInFilesVisitor.lambda$1(ASTInFilesVisitor.java:148)
	at il.org.spartan.spartanizer.cmdline.ASTInFilesVisitor$$Lambda$175/373182087.accept(Unknown Source)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at il.org.spartan.spartanizer.cmdline.ASTInFilesVisitor.visitLocation(ASTInFilesVisitor.java:148)
	at il.org.spartan.spartanizer.cmdline.ASTInFilesVisitor.lambda$0(ASTInFilesVisitor.java:121)
	at il.org.spartan.spartanizer.cmdline.ASTInFilesVisitor$$Lambda$173/1169794610.accept(Unknown Source)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at il.org.spartan.spartanizer.cmdline.ASTInFilesVisitor.visitAll(ASTInFilesVisitor.java:118)
	at il.org.spartan.spartanizer.cmdline.tables.Table_Summary.main(Table_Summary.java:60)`
```

**Comment by M4tt30rru** [comment]
Nothing changes if I use different (higher) values for the VM parameters -Xms and -Xmx

**Comment by M4tt30rru** [comment]
It seems to be related to the FileUtils.read method. In the following instruction 
```
    try (@NotNull BufferedReader reader = new BufferedReader(new FileReader(f))) {
      for (final String line = reader.readLine(); line != null;)
        $.append(line).append(ls);
    }
```
it keeps getting the first line again and again (it does not go over the first line) filling up the memory heap. It seems to work better with the following instruction:

```
    try (@NotNull BufferedReader reader = new BufferedReader(new FileReader(f))) {
      for(;;){
        String line = reader.readLine();
        if(line == null)
          break;
        $.append(line).append(ls);
      }
    }
```

**Comment by OriRoth** [comment]
Yes, a loop update seems to be missing:
```Java
try (@NotNull BufferedReader reader = new BufferedReader(new FileReader(f))) {
  for (String line = reader.readLine(); line != null; line = reader.readLine())
    $.append(line).append(ls);
}
```
Why didn't it solved the issue? (Also for #1308)
Notice that `FileUtils` are located in `spartan` (I think), so you'll need to `mvn package` it into `Spartanizer/lib` to see the changes.

**Comment by M4tt30rru** [comment]
Yes, both the solutions work.

**Comment by M4tt30rru** [comment]
Unfortunately in this very moment both the new fluen.ly spartan libraries (after packaging them) when used on the spartan plugin (missing references). As a workaround I am using the FilesUtils class on spartanizer.

**Comment by OriRoth** [comment]
FYI, I and @RoeiRaz are currently working on putting all of these projects under one repository. After it has been done there should not be such problems.

**Comment by M4tt30rru** [comment]
Closing
