### ISSUE TITLE
FluentSetter causes null pointer exception

### ISSUE THREAD

**Issue by RoeyMaor** [SpartanRefactoring/Main#1484]
disabling fluentSetter in the controller solves the issue
also, make sure to disable rename to cent as it is marked as under construction and will cause other problems

null
java.lang.NullPointerException
	at il.org.spartan.Leonidas.plugin.leonidas.Matcher.lambda$getMatchingResult$8(Matcher.java:206)
	at java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90)
	at java.util.HashMap$KeySpliterator.tryAdvance(HashMap.java:1569)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.allMatch(ReferencePipeline.java:454)
	at il.org.spartan.Leonidas.plugin.leonidas.Matcher.getMatchingResult(Matcher.java:205)
	at il.org.spartan.Leonidas.plugin.leonidas.Matcher.match(Matcher.java:45)
	at il.org.spartan.Leonidas.plugin.tippers.LeonidasTipper.canTip(LeonidasTipper.java:56)
	at il.org.spartan.Leonidas.plugin.Toolbox.lambda$executeAllTippers$17(Toolbox.java:195)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174)
	at java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464)
	at il.org.spartan.Leonidas.plugin.Toolbox.executeAllTippers(Toolbox.java:196)
	at il.org.spartan.Leonidas.plugin.Spartanizer$1.visitElement(Spartanizer.java:32)
	at com.intellij.psi.JavaElementVisitor.visitClass(JavaElementVisitor.java:54)
	at com.intellij.psi.impl.source.PsiClassImpl.accept(PsiClassImpl.java:469)
	at com.intellij.psi.impl.source.tree.CompositePsiElement.acceptChildren(CompositePsiElement.java:81)
	at com.intellij.psi.JavaRecursiveElementVisitor.visitElement(JavaRecursiveElementVisitor.java:43)
	at il.org.spartan.Leonidas.plugin.Spartanizer$1.visitElement(Spartanizer.java:31)
	at com.intellij.psi.JavaElementVisitor.visitStatement(JavaElementVisitor.java:271)
	at com.intellij.psi.JavaElementVisitor.visitDeclarationStatement(JavaElementVisitor.java:78)
	at com.intellij.psi.impl.source.tree.java.PsiDeclarationStatementImpl.accept(PsiDeclarationStatementImpl.java:89)
	at com.intellij.psi.impl.source.tree.LazyParseablePsiElement.acceptChildren(LazyParseablePsiElement.java:106)
	at com.intellij.psi.JavaRecursiveElementVisitor.visitElement(JavaRecursiveElementVisitor.java:43)
	at il.org.spartan.Leonidas.plugin.Spartanizer$1.visitElement(Spartanizer.java:31)
	at com.intellij.psi.JavaElementVisitor.visitCodeBlock(JavaElementVisitor.java:66)
	at com.intellij.psi.impl.source.tree.java.PsiCodeBlockImpl.accept(PsiCodeBlockImpl.java:202)
	at com.intellij.psi.impl.source.tree.SharedImplUtil.acceptChildren(SharedImplUtil.java:200)
	at com.intellij.psi.impl.source.JavaStubPsiElement.acceptChildren(JavaStubPsiElement.java:168)
	at com.intellij.psi.JavaRecursiveElementVisitor.visitElement(JavaRecursiveElementVisitor.java:43)
	at il.org.spartan.Leonidas.plugin.Spartanizer$1.visitElement(Spartanizer.java:31)
	at com.intellij.psi.JavaElementVisitor.visitMethod(JavaElementVisitor.java:178)
	at com.intellij.psi.impl.source.PsiMethodImpl.accept(PsiMethodImpl.java:284)
	at com.intellij.psi.impl.source.tree.SharedImplUtil.acceptChildren(SharedImplUtil.java:200)
	at com.intellij.psi.impl.source.JavaStubPsiElement.acceptChildren(JavaStubPsiElement.java:168)
	at com.intellij.psi.JavaRecursiveElementVisitor.visitElement(JavaRecursiveElementVisitor.java:43)
	at il.org.spartan.Leonidas.plugin.Spartanizer$1.visitElement(Spartanizer.java:31)
	at com.intellij.psi.JavaElementVisitor.visitClass(JavaElementVisitor.java:54)
	at com.intellij.psi.impl.source.PsiClassImpl.accept(PsiClassImpl.java:469)
	at com.intellij.psi.impl.source.tree.SharedImplUtil.acceptChildren(SharedImplUtil.java:200)
	at com.intellij.psi.impl.source.PsiFileImpl.acceptChildren(PsiFileImpl.java:853)
	at com.intellij.psi.JavaRecursiveElementVisitor.visitElement(JavaRecursiveElementVisitor.java:43)
	at il.org.spartan.Leonidas.plugin.Spartanizer$1.visitElement(Spartanizer.java:31)
	at com.intellij.psi.PsiElementVisitor.visitFile(PsiElementVisitor.java:34)
	at com.intellij.psi.JavaElementVisitor.visitJavaFile(JavaElementVisitor.java:335)
	at com.intellij.psi.impl.source.PsiJavaFileBaseImpl.accept(PsiJavaFileBaseImpl.java:464)
	at il.org.spartan.Leonidas.plugin.Spartanizer.spartanizeFileOnePass(Spartanizer.java:28)
	at il.org.spartan.Leonidas.plugin.Spartanizer.spartanizeFileRecursively(Spartanizer.java:42)
	at il.org.spartan.Leonidas.plugin.SpartanizerAction.actionPerformed(SpartanizerAction.java:30)

**Comment by RoeyMaor** [comment]
until this is solved, make sure to disable this tipper in the toolbox controller to prevent dependent bugs (for example exceptions upon spartanizing a file)
