### ISSUE TITLE
if double not issues

### ISSUE THREAD

**Issue by RoeyMaor** [SpartanRefactoring/Main#1537]
IfDoubleNot should have affected the example:
``` java
boolean b = !(!(true));
```
but it didn't.

also, for the following example:
``` java
for(int i = 0; !(!(i< 20)) ; ++i){
	i+=1;
}
```
there is an exception:
``` java
ERROR: Assertion failed
java.lang.Throwable
	at com.intellij.openapi.diagnostic.Logger.assertTrue(Logger.java:168)
	at com.intellij.openapi.diagnostic.Logger.assertTrue(Logger.java:177)
	at com.intellij.psi.impl.source.tree.CompositePsiElement.deleteChildRange(CompositePsiElement.java:205)
	at il.org.spartan.Leonidas.auxilary_layer.PsiRewrite$2.run(PsiRewrite.java:57)
	at com.intellij.openapi.command.WriteCommandAction$Simple.run(WriteCommandAction.java:234)
	at com.intellij.openapi.application.RunResult.run(RunResult.java:35)
	at com.intellij.openapi.command.WriteCommandAction.lambda$null$1(WriteCommandAction.java:171)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:1023)
	at com.intellij.openapi.command.WriteCommandAction.lambda$performWriteCommandAction$2(WriteCommandAction.java:170)
	at com.intellij.openapi.command.WriteCommandAction.lambda$doExecuteCommand$4(WriteCommandAction.java:210)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:149)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:119)
	at com.intellij.openapi.command.WriteCommandAction.doExecuteCommand(WriteCommandAction.java:212)
	at com.intellij.openapi.command.WriteCommandAction.performWriteCommandAction(WriteCommandAction.java:168)
	at com.intellij.openapi.command.WriteCommandAction.execute(WriteCommandAction.java:151)
	at il.org.spartan.Leonidas.auxilary_layer.PsiRewrite.deleteByRange(PsiRewrite.java:60)
	at il.org.spartan.Leonidas.plugin.leonidas.Replacer.replace(Replacer.java:83)
	at il.org.spartan.Leonidas.plugin.tippers.LeonidasTipper$1.go(LeonidasTipper.java:97)
	at il.org.spartan.Leonidas.plugin.Toolbox.executeSingleTipper(Toolbox.java:270)
	at il.org.spartan.Leonidas.plugin.tippers.TipperTest.check(TipperTest.java:129)
	at il.org.spartan.Leonidas.plugin.tippers.TestAllTippers.testTippers(TestAllTippers.java:24)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at junit.framework.TestCase.runTest(TestCase.java:176)
	at com.intellij.testFramework.UsefulTestCase.lambda$runTest$10(UsefulTestCase.java:311)
	at com.intellij.testFramework.PlatformTestCase.lambda$invokeTestRunnable$16(PlatformTestCase.java:697)
	at com.intellij.testFramework.PlatformTestCase.invokeTestRunnable(PlatformTestCase.java:709)
	at com.intellij.testFramework.UsefulTestCase.runTest(UsefulTestCase.java:330)
	at com.intellij.testFramework.PlatformTestCase.lambda$runBareImpl$15(PlatformTestCase.java:630)
	at com.intellij.testFramework.EdtTestUtil$Companion$runInEdtAndWait$1.invoke(EdtTestUtil.kt:29)
	at com.intellij.testFramework.EdtTestUtil$Companion$runInEdtAndWait$1.invoke(EdtTestUtil.kt:27)
	at com.intellij.testFramework.EdtTestUtilKt$sam$Runnable$b0f40f3d.run(EdtTestUtil.kt)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:301)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:343)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

```

**Comment by orenafek** [comment]
This bug doesn't seems to appear on my machine.
closing...
