### ISSUE TITLE
Leonidas: Exception in plugin

### ISSUE THREAD

**Issue by leyaniv** [SpartanRefactoring/Main#1611]
It happens every time I click on Leonidas -> Spartanize. Tried on few files.

![image](https://user-images.githubusercontent.com/11694372/27790164-0cb16348-5ff8-11e7-981c-bd631573759b.png)

```
null
java.lang.NullPointerException
	at il.org.spartan.Leonidas.plugin.Toolbox.executeAllTippers(Toolbox.java:195)
	at il.org.spartan.Leonidas.plugin.Spartanizer$1.visitElement(Spartanizer.java:35)
	at com.intellij.psi.JavaElementVisitor.visitClass(JavaElementVisitor.java:54)
	at com.intellij.psi.JavaElementVisitor.visitAnonymousClass(JavaElementVisitor.java:22)
	at com.intellij.psi.impl.source.PsiAnonymousClassImpl.accept(PsiAnonymousClassImpl.java:179)
	at com.intellij.psi.impl.source.tree.CompositePsiElement.acceptChildren(CompositePsiElement.java:81)
	at com.intellij.psi.JavaRecursiveElementVisitor.visitElement(JavaRecursiveElementVisitor.java:43)
	at il.org.spartan.Leonidas.plugin.Spartanizer$1.visitElement(Spartanizer.java:34)
	at com.intellij.psi.JavaElementVisitor.visitExpression(JavaElementVisitor.java:102)
	at com.intellij.psi.JavaElementVisitor.visitCallExpression(JavaElementVisitor.java:186)
	at com.intellij.psi.JavaElementVisitor.visitNewExpression(JavaElementVisitor.java:194)
	at com.intellij.psi.impl.source.tree.java.PsiNewExpressionImpl.accept(PsiNewExpressionImpl.java:384)
	at com.intellij.psi.impl.source.tree.CompositePsiElement.acceptChildren(CompositePsiElement.java:81)
	at com.intellij.psi.JavaRecursiveElementVisitor.visitElement(JavaRecursiveElementVisitor.java:43)
	at il.org.spartan.Leonidas.plugin.Spartanizer$1.visitElement(Spartanizer.java:34)
	at com.intellij.psi.JavaElementVisitor.visitExpressionList(JavaElementVisitor.java:106)
	at com.intellij.psi.impl.source.tree.java.PsiExpressionListImpl.accept(PsiExpressionListImpl.java:142)
	at com.intellij.psi.impl.source.tree.CompositePsiElement.acceptChildren(CompositePsiElement.java:81)
	at com.intellij.psi.JavaRecursiveElementVisitor.visitElement(JavaRecursiveElementVisitor.java:43)
	at il.org.spartan.Leonidas.plugin.Spartanizer$1.visitElement(Spartanizer.java:34)
	at com.intellij.psi.JavaElementVisitor.visitExpression(JavaElementVisitor.java:102)
	at com.intellij.psi.JavaElementVisitor.visitCallExpression(JavaElementVisitor.java:186)
	at com.intellij.psi.JavaElementVisitor.visitMethodCallExpression(JavaElementVisitor.java:182)
	at com.intellij.psi.impl.source.tree.java.PsiMethodCallExpressionImpl.accept(PsiMethodCallExpressionImpl.java:141)
	at com.intellij.psi.impl.source.tree.CompositePsiElement.acceptChildren(CompositePsiElement.java:81)
	at com.intellij.psi.JavaRecursiveElementVisitor.visitElement(JavaRecursiveElementVisitor.java:43)
	at il.org.spartan.Leonidas.plugin.Spartanizer$1.visitElement(Spartanizer.java:34)
	at com.intellij.psi.JavaElementVisitor.visitStatement(JavaElementVisitor.java:271)
	at com.intellij.psi.JavaElementVisitor.visitExpressionStatement(JavaElementVisitor.java:114)
	at com.intellij.psi.impl.source.tree.java.PsiExpressionStatementImpl.accept(PsiExpressionStatementImpl.java:77)
	at com.intellij.psi.impl.source.tree.LazyParseablePsiElement.acceptChildren(LazyParseablePsiElement.java:106)
	at com.intellij.psi.JavaRecursiveElementVisitor.visitElement(JavaRecursiveElementVisitor.java:43)
	at il.org.spartan.Leonidas.plugin.Spartanizer$1.visitElement(Spartanizer.java:34)
	at com.intellij.psi.JavaElementVisitor.visitCodeBlock(JavaElementVisitor.java:66)
	at com.intellij.psi.impl.source.tree.java.PsiCodeBlockImpl.accept(PsiCodeBlockImpl.java:202)
	at com.intellij.psi.impl.source.tree.SharedImplUtil.acceptChildren(SharedImplUtil.java:200)
	at com.intellij.psi.impl.source.JavaStubPsiElement.acceptChildren(JavaStubPsiElement.java:168)
	at com.intellij.psi.JavaRecursiveElementVisitor.visitElement(JavaRecursiveElementVisitor.java:43)
	at il.org.spartan.Leonidas.plugin.Spartanizer$1.visitElement(Spartanizer.java:34)
	at com.intellij.psi.JavaElementVisitor.visitMethod(JavaElementVisitor.java:178)
	at com.intellij.psi.impl.source.PsiMethodImpl.accept(PsiMethodImpl.java:284)
	at com.intellij.psi.impl.source.tree.SharedImplUtil.acceptChildren(SharedImplUtil.java:200)
	at com.intellij.psi.impl.source.JavaStubPsiElement.acceptChildren(JavaStubPsiElement.java:168)
	at com.intellij.psi.JavaRecursiveElementVisitor.visitElement(JavaRecursiveElementVisitor.java:43)
	at il.org.spartan.Leonidas.plugin.Spartanizer$1.visitElement(Spartanizer.java:34)
	at com.intellij.psi.JavaElementVisitor.visitClass(JavaElementVisitor.java:54)
	at com.intellij.psi.impl.source.PsiClassImpl.accept(PsiClassImpl.java:469)
	at com.intellij.psi.impl.source.tree.SharedImplUtil.acceptChildren(SharedImplUtil.java:200)
	at com.intellij.psi.impl.source.PsiFileImpl.acceptChildren(PsiFileImpl.java:857)
	at com.intellij.psi.JavaRecursiveElementVisitor.visitElement(JavaRecursiveElementVisitor.java:43)
	at il.org.spartan.Leonidas.plugin.Spartanizer$1.visitElement(Spartanizer.java:34)
	at com.intellij.psi.PsiElementVisitor.visitFile(PsiElementVisitor.java:34)
	at com.intellij.psi.JavaElementVisitor.visitJavaFile(JavaElementVisitor.java:335)
	at com.intellij.psi.impl.source.PsiJavaFileBaseImpl.accept(PsiJavaFileBaseImpl.java:464)
	at il.org.spartan.Leonidas.plugin.Spartanizer.spartanizeFileOnePass(Spartanizer.java:31)
	at il.org.spartan.Leonidas.plugin.SpartanizerAction.actionPerformed(SpartanizerAction.java:30)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:215)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:232)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.lambda$actionPerformed$0(ActionMenuItem.java:309)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.runOnOwnContext(FocusManagerImpl.java:929)
	at com.intellij.openapi.wm.impl.IdeFocusManagerImpl.runOnOwnContext(IdeFocusManagerImpl.java:136)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.actionPerformed(ActionMenuItem.java:299)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.lambda$fireActionPerformed$0(ActionMenuItem.java:116)
	at com.intellij.openapi.application.TransactionGuardImpl.runSyncTransaction(TransactionGuardImpl.java:86)
	at com.intellij.openapi.application.TransactionGuardImpl.lambda$submitTransaction$1(TransactionGuardImpl.java:109)
	at com.intellij.openapi.application.TransactionGuardImpl.submitTransaction(TransactionGuardImpl.java:118)
	at com.intellij.openapi.application.TransactionGuard.submitTransaction(TransactionGuard.java:122)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.fireActionPerformed(ActionMenuItem.java:116)
	at com.intellij.ui.plaf.beg.BegMenuItemUI.doClick(BegMenuItemUI.java:513)
	at com.intellij.ui.plaf.beg.BegMenuItemUI.access$300(BegMenuItemUI.java:45)
	at com.intellij.ui.plaf.beg.BegMenuItemUI$MyMouseInputHandler.mouseReleased(BegMenuItemUI.java:533)
	at java.awt.Component.processMouseEvent(Component.java:6541)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6306)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4897)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4719)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4719)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:737)
	at java.awt.EventQueue$4.run(EventQueue.java:735)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:827)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:651)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:365)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by amirsagiv83** [comment]
Hi,

Youre still on the wrong release.

There is no spratanize button on the newest release..

the release is SpartanizeJ1.2
